### PR TITLE
[fix] Special characters in captions saved correctly

### PR DESCRIPTION
**Pull request by Galixte**
Minor update for teamsecurity_module.php

### CODE REVIEW

**Comment by VSEphpbb** [comment]
You do not use utf8_normailize on the request class. It already normalizes utf8 characters.

**Comment by VSEphpbb** [comment]
Would you be so kind as to update the .travis.yml file too and add `sudo: required` to the top of the file please? That will fix the failing tests.

**Comment by Galixte** [comment]
OK i have update the .travis.yml. 

You say it already normalizes utf8 characters but without this fixe the special characters are not saved correctly. Maybe there is an other method.

**Comment by VSEphpbb** [comment]
Get rid of the utf8_normalize... You just need to leave the third argument set to true in the request like you did in this fix. I just tested that and it works.

**Comment by Galixte** [comment]
Thanks, now it's OK.

**Pull request merged**
