### PR TITLE
Fixes and updates

### PR DESCRIPTION
**Pull request by VSEphpbb**

### CODE REVIEW

**Comment by michaelcullum** [comment]
Also. Why?

**Comment by VSEphpbb** [comment]
Duplicate conditional code. Scores poorly in metrics. High complexity.

**Comment by michaelcullum** [comment]
This is really ugly, before it was much clearer. This is also considered more complex as you have exactly the same conditional operations, but an extra function call in depth. Metrics aren't everything.

**Comment by VSEphpbb** [comment]
🆗

**Pull request merged**
